### ISSUE TITLE
Rework settings window to allow for more settings

### ISSUE THREAD

**Issue by Blightbuster** [Blightbuster/RatScanner#13]
Proposed are these three reworks:

1. Add buttons to open seperate new sub-setting windows
2. Expand the height of the settings window
3. Add tabs to the settings window

![](https://user-images.githubusercontent.com/24388294/94378459-296a0400-012a-11eb-8ec6-effceb266013.png)

I personally prefer #3 because of the expandability and logical seperation but would like to hear some feedback / other suggestions on reworking the settings window.

**Comment by Quipex** [comment]
Third one looks most handy for me also. Needs some styling tweaks tho.
1. I'd remove the white stripe separating tabs from content
2. Possibly added more padding both on top and bottom of the labels. Not sure tho 😅

I hope it handles overflow out of the box?

**Comment by Blightbuster** [comment]
I did a sample implementation and it currently looks like this with overflow:
![image](https://user-images.githubusercontent.com/24388294/94447233-dc2d7700-01a9-11eb-97ca-985edd6e8520.png)

and without overflow:
![image](https://user-images.githubusercontent.com/24388294/94447395-fe26f980-01a9-11eb-9251-99025d44fdc6.png)

But I could also imagine it without the surrounding white box (My personal favorite).
![image](https://user-images.githubusercontent.com/24388294/94448259-fae03d80-01aa-11eb-91e3-ce42c2240244.png)
![image](https://user-images.githubusercontent.com/24388294/94448307-09c6f000-01ab-11eb-8a23-fa36172cdd1d.png)

**Comment by Blightbuster** [comment]
Closed by f2f19c4866a4ba73929466ec76ec261e108232f2
