### ISSUE TITLE
Shift+Click is still captured when Enable Icon Scan disabled

### ISSUE THREAD

**Issue by dartonias** [Blightbuster/RatScanner#18]
**Describe the bug**
Whatever the key combo for "Enable Icon Scan" is used, even if the feature is disabled this key combo is captured by the program and not sent on wards.

**To Reproduce**
1. Start the program normally
2. Disable Enable Icon Scan in the settings
4. Hold shift, left click, see that the underlying behavior in Tarkov is missing (for me, this is hold breath and fire gun)

**Expected behavior**
When Enable Icon Scan is disabled, the program no longer captures that key combination

**Comment by Blightbuster** [comment]
Fix will be merged into master when next release is ready.
