### ISSUE TITLE
Image Alignment off/no price on item

### ISSUE THREAD

**Issue by Sudo-Sys** [Blightbuster/RatScanner#21]
When using shift click on any items it's not showing the price in upper left corner of the actual item like in the readme file.  It just updates in the app, and clicking items towards the right side of screen causes the price to appear off the screen.
I'm using 2560x1440 and Resolution set to QHD in app.  All settings enabled under scanning and Minimal UI.  Everything ran as admin.

**Shift clicking on AVS rig on left**
![Capture](https://user-images.githubusercontent.com/28811595/95012957-76eee100-0602-11eb-9d84-20115487d4a6.PNG)

**Shift clicking on Trooper in middle causes it to go mostly off screen, anything to right of that it goes completely off screen.**
![capture 2](https://user-images.githubusercontent.com/28811595/95013040-262bb800-0603-11eb-8348-55116d477f7e.PNG)

**Comment by Blightbuster** [comment]
Are you sure that your using the QHD setting? It looks like the items which are displayed are alot bigger than displayed in your stash which hints to the resolution not being configured correctly.
Maybe its also a problem with your screen being not actually set at 2560x1440 but rather 1920x1080. Please double check this inside Nvidia Control Panel (if using a Nvidia GPU) and inside the graphics settings of tarkov.

**Comment by Sudo-Sys** [comment]
I've checked in windows display settings, nvidia control panel and in game.  All are set to 2560x1440.

![resolution](https://user-images.githubusercontent.com/28811595/95013955-49596600-0609-11eb-9eb5-747867285647.PNG)

**Comment by Blightbuster** [comment]
Ok I just tried myself on your screenshot with resolution set to QHD and it works without any issues.
![image](https://user-images.githubusercontent.com/24388294/95126682-250b9f80-0757-11eb-965f-14a418b6a6b3.png)

Maybe dump question but are you sure that you clicked on "Save" after changing the resolution?

**Comment by huaiyi1996** [comment]
same problem, I was thinking if it was the problem of scaling like the default 150% and the 100%.

**Comment by huaiyi1996** [comment]
Verified, it's the issue of system scaling, the default scaling settng for QHD 4k is 150%, but we will need to set the system scaling to 100%, so that the picture will cover normally

**Comment by huaiyi1996** [comment]
So the issue should be that this tool need to adapt the default 4k QHD and 150% scaling setting.

**Comment by Sudo-Sys** [comment]
Yes at 2k I use 125% scaling just so everything is readable.  Changing this to 100% fixes the problem but it's not something I can leave on.

**Comment by Blightbuster** [comment]
Oh yeah that makes sense. Thanks for figuring it out <3

I'll try to make a fix for it.

**Comment by Blightbuster** [comment]
Ok I have a fix ready but would like it to be tested by one of you before pushing it.
Id appreciate it if you could contact me on the [discord](https://discord.gg/aHZf7aP) so I can send you the development buid.

**Comment by Blightbuster** [comment]
Fixed in next release.

Please reopen this issue if it is still not working correctly after the next release.

**Comment by huaiyi1996** [comment]
Hi there,
Just replaced the 2.2.2 version, then it's still not working with 4k 150%.
I've two screens here(main:4k 150%, 2nd:2k 100%), playing EFT in the main screen.
<img width="278" alt="test" src="https://user-images.githubusercontent.com/14867886/95489264-3c51c380-09c9-11eb-8954-e40811186e44.png">

The picture covering is still missing the place, and the picture is also larger than it  should be~

**Comment by Blightbuster** [comment]
The fix will be in the next release. That will be 2.3.0 probably released in the next 25h
