### ISSUE TITLE
Add an option to use a less obtrusive overlay to display price

### ISSUE THREAD

**Issue by greensmyname** [Blightbuster/RatScanner#5]
My suggestion is to add an optionable toggle for users to select a smaller and more compact overlay with the following features:

- smaller overlay
- in settings: user selected toggleable data values
  (add or remove: price, day price, week price, price per slot, trader, trader buy price)
- in settings: user choses where it is on the screen
- in settings: font size, color, normal/bold
![unobtrusive mode](https://user-images.githubusercontent.com/68490933/93951846-722e5100-fd15-11ea-8dcf-cc7d53b5ec1d.png)

**Comment by greensmyname** [comment]
replace Trader in the right side with Therapist, forgot to do that in the example

**Comment by Blightbuster** [comment]
Would this replace the current ui ( like a step between having it open and minimizing it ), or would it co-exist with it as some sort of second tool tip?

What do you think of instead making current tooltip customizable?
Users could be able to choose what is shown in the tooltip, fix its position to a screen corner and adjust other things such as transparancy.

**Comment by greensmyname** [comment]
I think it should be an option to pick between the current UI and this
smaller mode.

Personally I run your current tool in always on top mode, but it's a little
large to be on top of the game in its current state.
If you were able to just have white / black (chosable by user dependant on
day/night raid) text with no GUI as an overlay, that would work better for
me personally.

Customizing the current tooltip would also work, but I would love to see a
very minimal approach as an option as well.

IMO, the window should be able to be dragged by the user, then locked in
place, rather than just fixed to corner, so it could work with users that
stream and have different overlays.

**Comment by Blightbuster** [comment]
Ok I see your issue :smile:
I just have the main window on my second monitor, which works out great, but that's obviously not possible for people using a single monitor.

**Comment by Blightbuster** [comment]
I started implementing the feature [here](/blightbuster/ratscanner/tree/feature/Minimal-UI)

I propose this to be the ui when all data options are ticked. This means some data from the main window like links or the icon preview wont be avaible in the minimal ui.
![image](https://user-images.githubusercontent.com/24388294/94352486-efcfc500-0065-11eb-890f-6c7f89dd25ae.png)

**Comment by Blightbuster** [comment]
Closed by f22c921fcf4b8c9eca4188b49fb7bbc9c4a7fa83
